# Generated by Django 2.1 on 2019-04-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
